version: '3.9'

services:

  go-app:
    build: .
    container_name: go-app
    env_file: .env
    depends_on:
      - 'mongodb'
    environment:
      MONGODB_URL: "mongodb://${DB_USER}:${DB_PASSWORD}@mongodb:27017"
    volumes:
      - '.:/template'

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file: .env
    depends_on:
      - 'mongodb'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: $DB_USER
      ME_CONFIG_BASICAUTH_PASSWORD: $DB_PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD
      ME_CONFIG_MONGODB_URL: "mongodb://mongodb:27017/writeapp?authSource=admin"
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
      MONGO_INITDB_USERNAME: $DB_USER
      MONGO_INITDB_PASSWORD: $DB_PASSWORD
      MONGO_INITDB_DATABASE: $DB_NAME
      INITDB_COLLECTION: $DB_COLLECTION
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
